export default {
  name: 'CodeSeven',
  database: 'MySQL',
  types: ['API'],
  camelCaseStrategy: true,
  mailEnabled: false,
  mailers: ['SMTP'],
  defaultMailer: 'SMTP',
  storageEnabled: false,
  storageDrivers: ['Local'],
  defaultStorageDriver: 'Local',
  tech: { backend: 'Adonis', frontend: 'Buefy' },
  generate: {
    api: { generate: true, crud: true, test: true },
    spa: { generate: true, crud: true },
    app: { generate: false },
    website: { generate: false },
  },
  auth: {
    register: true,
    passwordReset: false,
    passwordChange: true,
    table: {
      name: 'User',
      generateUI: true,
      generateController: true,
      generateModel: true,
      generateMigration: false,
      defaultColumn: 'Name',
      timestamps: true,
      generateRoute: true,
      indexColumns: ['Name', 'Email'],
      operations: {
        index: true,
        create: true,
        store: true,
        edit: true,
        show: true,
        update: true,
        destroy: true,
        storeMany: true,
        destroyMany: true,
      },
      customOperations: [],
      relations: [
        { type: 'HasMany', withModel: 'Tag', required: true, showInputOnCreatePage: false },
        { type: 'HasMany', withModel: 'Post', required: true, showInputOnCreatePage: false },
      ],
      columns: [],
    },
  },
  tenantSettings: { user: 1, tenant: 0 },
  rbac: {
    enabled: false,
    multipleRoles: false,
    roles: [{ name: 'Admin', description: 'User with full access to everything', default: false }],
    permissions: [],
    matrix: [{ role: 'Admin', permissions: [] }],
  },
  tables: [
    {
      name: 'Tag',
      generateUI: true,
      generateController: true,
      generateModel: true,
      generateMigration: true,
      defaultColumn: 'Name',
      timestamps: true,
      generateRoute: true,
      singleton: false,
      routeParents: [],
      indexColumns: ['Name'],
      operations: {
        index: true,
        create: true,
        store: true,
        edit: true,
        show: true,
        update: true,
        destroy: true,
        storeMany: true,
        destroyMany: true,
      },
      customOperations: [],
      relations: [
        { type: 'ManyToMany', withModel: 'Post', required: true, showInputOnCreatePage: false },
        { type: 'BelongsTo', withModel: '$auth', required: true, showInputOnCreatePage: false },
      ],
      columns: [
        {
          name: 'Name',
          type: 'String',
          meta: {
            required: true,
            maxLength: 128,
            expose: true,
            filterable: false,
            sortable: false,
            trim: true,
          },
          input: {
            type: 'Input',
            decimal: { step: 'any' },
            select: { types: ['object', 'string', 'number'], type: 'string', options: [] },
          },
        },
      ],
    },
    {
      name: 'Post',
      generateUI: true,
      generateController: true,
      generateModel: true,
      generateMigration: true,
      defaultColumn: 'Name',
      timestamps: true,
      generateRoute: true,
      singleton: false,
      routeParents: [],
      indexColumns: ['Name'],
      operations: {
        index: true,
        create: true,
        store: true,
        edit: true,
        show: true,
        update: true,
        destroy: true,
        storeMany: true,
        destroyMany: true,
      },
      customOperations: [],
      relations: [
        { type: 'ManyToMany', withModel: 'Tag', required: true, showInputOnCreatePage: true },
        { type: 'BelongsTo', withModel: '$auth', required: true, showInputOnCreatePage: false },
      ],
      columns: [
        {
          name: 'Name',
          type: 'String',
          meta: {
            required: true,
            minLength: 2,
            expose: true,
            filterable: false,
            sortable: false,
            trim: true,
          },
          input: {
            type: 'Input',
            decimal: { step: 'any' },
            select: { types: ['object', 'string', 'number'], type: 'string', options: [] },
          },
        },
      ],
    },
  ],
}
